### ISSUE TITLE
Students page limited to 50

### ISSUE THREAD

**Issue by aaronmahlke** [dokedu/frontend#34]
The students page currently doesn't seem to have pagination while also being limited to 50 students.
Once you have more students you are not able to view them besides searching for them.

**Implementation of current limit to 50:**
https://github.com/dokedu/frontend/blob/834c8127230c2dec311a23af84ee73cedf8f0895/src/pages/school/students.vue#L126C9-L126C19

Pagination should be implemented so that the user can get an overview of all students.

**Comment by tomhaerter** [comment]
@aaronmahlke thank you for highlighting this issue with the student's page limit. For a swift resolution, we could increase the maximum to 500 students, a number that should cover most school's needs.

Infinite scrolling is a feature we’re considering for a more scalable, long-term solution, seeing as it has worked well elsewhere in our application. Your input is invaluable to us in making these improvements
